[project]
name = "Gmonte"  # ここにプロジェクトの名前を入力
version = "0.1.0"
description = "Your project description"
authors = [{name = "Yuho Shimano", email= "shimano.y.shimano@gmail.com"}]




[project.scripts]
Gmonte  = "Gmonte.montecarlo:main"
